theme: jekyll-theme-architect
markdown: kramdown
plugins:
  - jekyll-sitemap
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
incremental: false
highlighter: rouge
gist:
  noscript: false
timezone: Asia/Tokyo